spring.application.name=rent.tools.api

# Porta dinamicamente injetada pelo Render (fallback local 8080)
server.port=${PORT:8080}

# Banco de Dados (Variáveis de Ambiente)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA e Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.format-sql=true